### PR TITLE
Implement explicit root rules declaration

### PR DESCRIPTION
**Pull request by vbmacher**

### CODE REVIEW

**Comment by vbmacher** [comment]
There are missing checks for detection multiple names of the same rule

**Comment by vbmacher** [comment]
A deduplicate root rules visitor has been implemented

**Comment by vbmacher** [comment]
TODO: root rules which have multiple names are called possibly by wrong name. Rule names in root rule declaration are translated into Rule objects and the names are forgotten. Then in decoder rules are called as `rule_first_name(start, RULE_FIRST_NAME)` instead of `rule_first_name(start, RULE_NAME_USED_IN_ROOT_RULE_DECLARATION)`

**Comment by vbmacher** [comment]
> TODO: root rules which have multiple names are called possibly by wrong name. Rule names in root rule declaration are translated into Rule objects and the names are forgotten. Then in decoder rules are called as `rule_first_name(start, RULE_FIRST_NAME)` instead of `rule_first_name(start, RULE_NAME_USED_IN_ROOT_RULE_DECLARATION)`

It's done now.

**Review by sulir — APPROVED** [review]

**Pull request merged**
